server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: xoroj
    password: secret

  jpa:
    hibernate:
      ddl-auto: create-drop   # or 'update' during dev if you don't want drop on shutdown
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
