spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  
  jpa:
    open-in-view: true #change in prod
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  thread:
    virtual:
      enabled: true
server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,text/event-stream
    min-response-size: 512
  http2:
    enabled: true