
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # or 'update' during dev if you don't want drop on shutdown else create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true